name: CICD

on:
  push:
    branches: [ "workflow" ]
    paths-ignore:
    - README.md

  pull_request:
    branches: [ "workflow" ]
    paths-ignore:
    - README.md
  
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      
      - name: Linux - Build
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          flutter pub get
          flutter config --enable-linux-desktop
          flutter build linux

      - name: Windows - Build
        if: matrix.os == 'windows-latest'
        run: |
            flutter pub get
            flutter config --enable-windows-desktop
            flutter build windows

      - name: MacOS - Build
        if: matrix.os == 'macos-latest'
        run: |
            flutter pub get
            flutter config --enable-macos-desktop
            flutter build macos

      - name: Linux - Upload Build Artifact
        uses: actions/upload-artifact@v3
        if: matrix.os == 'ubuntu-latest'
        with:
          name: linux
          path: ${{github.workspace}}/build/linux/x64/release/bundle/

      - name: Windows - Upload Build Artifact
        uses: actions/upload-artifact@v3
        if: matrix.os == 'windows-latest'
        with:
          name: windows
          path: ${{github.workspace}}/build/windows/runner/Release

      - name: MacOS - Upload Build Artifact
        uses: actions/upload-artifact@v3
        if: matrix.os == 'macos-latest'
        with:
          name: macos
          path: ${{github.workspace}}/build/macos/Build/Products/Release