name: Linux

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - windows/
      - macos/
      - .github/workflows/windows.yml
      - .github/workflows/macos.yml
      - README.md
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - windows/
      - macos/
      - .github/workflows/windows.yml
      - .github/workflows/macos.yml
      - README.md

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
    - run: flutter config --enable-linux-desktop
    - run: flutter pub get
    - run: flutter build linux
    - uses: actions/upload-artifact@v3
      with:
        name: bundle
        path: ${{github.workspace}}/build/linux/x64/release/bundle/
