name: Windows

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - macos/
      - linux/
      - .github/workflows/macos.yml
      - .github/workflows/linux.yml
      - README.md
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - macos/
      - linux/
      - .github/workflows/macos.yml
      - .github/workflows/linux.yml
      - README.md

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter config --enable-windows-desktop
    - run: flutter pub get
    - run: flutter build windows
    - uses: actions/upload-artifact@v3
      with:
        name: bundle
        path: ${{github.workspace}}/build/windows/runner/Release
